- src/Movement/Grid.cpp
The first one is before, the second after the first fix and the third after the last one.
> Grid leveling bugfixes

- src/GCodes/GCodes.cpp
- src/Movement/Grid.cpp
- src/Movement/Grid.h
There was one issue remaining with the grid leveling: points which could not be probed will be clamped down to 0 for the heightmap interpolation. A user of the grid leveling could avoid this problem by setting the leveling area settings so that all points will be probed. But this is non-obvious for a user and also leaves another problem: the area which can't be probed will be now clamped to the last measured one.
Taking into account that the z-sensor might be far away from the nozzle (on a BigBox it's 65mm) and the fact that one can't set the probing spacing separately for X and Y the resulting unmeasured border might be quite large.
My solution to this is: extrapolating the missing unprobed points by using linear least squares in 3d-space and derive a plane from it. The …
> Grid leveling bugfixes #2

- src/GCodes/GCodes.cpp
Documentation says uploading html file is deprecated but, it is available for use so I fix it.
If the iteration encounters with a char that is in eofstring and then encounters a char that is not in the eofstring, method writes the full eofstring to the file which is resulting a wrong output.
For example this input:
```
ABCDEF
GH
JKLMN
```
> Fix WriteHTMLToFile resulting wrong write

- src/Heating/Pid.cpp
Currently, max pwm parameter in auto tune is ignored after the auto tune is completed. This PR makes max pwm persistent. So after the auto tune is completed, correct pwm is reported and saved to the config-override file.
> Save max pwm after the auto tune is completed

- src/Movement/Kinematics/HangprinterKinematics.cpp
Same bugfix as #177 but now onto the v2-dev branch.
> Fixes typo in Zab assignment

- src/Fans/DotStarLed.h
- src/StepperDrivers/TMC22xx/TMC22xx.cpp
- src/StepperDrivers/TMC2660/TMC2660.cpp
On Linux machines (and most probably also on MacOS) there was a compiler error because it could not find the import of `ReprapFirmware.h` because the file is named `RepRapFirmware.h` (note the capital R of "Rap"). Windows does not care but case-sensitive file-systems do.
> Fix include for case-sensitive file-systems

- src/Fans/Fan.cpp
- src/Fans/Fan.h
This closes
https://forum.duet3d.com/topic/5726/m106-maximum-fan-speed-setting and https://forum.duet3d.com/topic/5370/m106-feature-request-limit-max-pwm-parameter
I have **not** compiled the code but as simple as this change is I don't think this was necessary.
AKAICT, these are the only two places where changes are needed, right?
Once you accept this PR I will also add this to Gcode wiki at dozuki for Duet and reprap.org to "officially" reserve the `M` parameter for `M106`.
> Add a maximum fan speed parameter and enforce it

- src/DuetNG/Pins_DuetNG.h
Just removes a small annoyance when switching back and forth between compiling with and without RTOS.
> Automatically set DHT sensor support to 0 when compiling no RTOS

- src/GCodes/GCodes2.cpp
- src/Heating/Heat.cpp
- src/Heating/Heat.h
- src/RepRap.cpp
- src/Tools/Tool.cpp
This fixes https://forum.duet3d.com/topic/5735/set-extrusion-min-temp
I don't know if this was intentional in the first to have these values hard-coded and not configurable so I implemented this as a "you decide", i.e. I won't be mad if you decline this PR - in that case it was just a nice practice for my C++ skills as well as getting more into the code structure of RRF. :-)
So as I said, you decide. ;-)
As with the other PR that needs amendment of the G-code wiki: if you decide to merge, I will also do those changes.
> Allow configuration of extrusion and retraction minimum temperatures

- src/Heating/Sensors/CurrentLoopTemperatureSensor.cpp
- src/Heating/Sensors/CurrentLoopTemperatureSensor.h
This change enables the use of all channels on the ADC MCP3204 & MCP3208 devices for the Current Loop Temperature Sensors (X300-X399). You can now specify a channel select independent of the X value so all channels on the chip are available. Additionally a new value for W is enabled to allow for single or differential pairs to be selected.
Channel select = "C"
C0 (default), C1, C2, C3... etc up to C7 on MCP3208 device.
Single / Differential select = "W".
W0 (single, default)
W1 (differential)
Forum discussion: https://forum.duet3d.com/topic/7151/linear-adc-thermocouple-improvements
> CurrentLoopTemperature Multiple Channels on Chip

- src/CAN/CanMessageBuffer.h
Fixes a typo in
```
#include "RepRapFirmware.h"
```
This makes the project compile.
Another fix that lets the project compile for me is to just comment out the line.
> Fixes typo

- src/GCodes/GCodes.cpp
- src/GCodes/GCodes2.cpp
- src/Platform.cpp
- src/Platform.h
This closes my request at: https://forum.duet3d.com/topic/8225/m92-parameter-to-indicate-microstepping
I was too impatient again. ;-)
I chose the parameter to be `Fnnn` just because I wanted to avoid `Mnnn` because of M-codes and `X` or `U` are already taken by axis names. So this is microstepping-`F`actor.
> Add a parameter Snnn to M92 that indicates the microstepping factor

- src/GCodes/GCodes.cpp
- src/RepRap.cpp
- src/RepRap.h
Also extend M500 P parameter to take multiple values separated by colon.
> Add M500 P10 to enable saving of manually entered tool offsets

- src/GCodes/GCodes3.cpp
- src/Movement/StraightProbeSettings.h
If the default probe is not defined and there is no `Pnnn` given to `G38.x` then this would lead to a `nullptr` dereference later.
> Fix nullptr dereference when default probe is not defined

- src/Heating/LocalHeater.cpp
https://forum.duet3d.com/topic/15276/proposed-change-to-heater-excursion-message
The temperature excursion message now looks something like:
"Heating fault on heater 1, temperature excursion exceeded
15°C.  Expected: 225°C.  Actual: 209°C"
> LocalHeater.cpp: Add expected and actual temps to fault msg

- BuildInstructions.md
- mention release tags as of v3.1
- tabularize project list
- linkify mentions of projects
- expand board specific dependency list, build configurations, and
build order
- add links to related projects
> Restructure BuildInstructions.md

- src/Networking/LwipEthernet/Lwip/src/netif/ppp/eap.c
This is an automatically generated security fix for a vulnerability detected in your code which is a variant of [CVE-2020-8597](https://nvd.nist.gov/vuln/detail/CVE-2020-8597). 
You can read in more detail about this vulnerability in [CERT Advisory VU#782301](https://kb.cert.org/vuls/id/782301/).
The vulnerability occurs because, given that `vallen` was checked to be less than `len`, it can never be the case that `vallen >= len + sizeof(rhostname)`. Therefore, `rhostname` never gets trimmed and the `rhostname` array may overflow.
While this PR was generated for your project automatically, the supporting analysis was performed and verified by the [GitHub Security Lab](https://securitylab.github.com/). 
The original finding was reported by Ilja Van Sprundel from IOActive.
The proposed patch …
> [SECURITY] Prevent `rhostname` array overflow

- src/Libraries/sd_mmc/ctrl_access.h
When building, got this error:
```
In file included from C:\eclipse\Firmware\CoreNG\cores\arduino/RingBuffer.h:23,
from C:\eclipse\Firmware\CoreNG\cores\arduino/UARTClass.h:23,
from C:\eclipse\Firmware\CoreNG\variants\same70/variant.h:40,
from C:\eclipse\Firmware\CoreNG\cores\arduino/Core.h:190,
from C:\eclipse\Firmware\RepRapFirmware\src/Libraries/sd_mmc/ctrl_access.h:76,
from ../src/Libraries/Fatfs/diskio.cpp:47:
c:\program files (x86)\gnu tools arm embedded\8 2018-q4-major\arm-none-eabi\include\c++\8.2.1\cstddef:68:3: error: template with C linkage
template<typename _IntegerType> struct __byte_operand { };
^~~~~~~~
In file included from ../src/Libraries/Fatfs/diskio.cpp:47:
C:\eclipse\Firmware\RepRapFirmware\src/Libraries/sd_mmc/ctrl_access.h:64:1: note: 'extern "C"' linkage started …
```
> Fix/extern "C" linkage nesting error

- src/CAN/ExpansionManager.h
- src/Configuration.h
- src/GCodes/GCodes.cpp
- src/GCodes/GCodes2.cpp
- src/GCodes/GCodes3.cpp
- src/GCodes/GCodes4.cpp
- src/Logger.cpp
- src/Logger.h
- src/MessageType.h
- src/Movement/Kinematics/HangprinterKinematics.cpp
- src/Movement/Kinematics/LinearDeltaKinematics.cpp
- src/Movement/Kinematics/ZLeadscrewKinematics.cpp
- src/Networking/HttpResponder.cpp
- src/Platform.cpp
- src/Platform.h
- src/RepRap.cpp
- src/Tasks.cpp
* Extend log levels from only 0 and 1 to 0 to 3
* Add log level to the object model as `state.logLevel`
* Use the two top bits in `MessageType` to represent log levels
* Add `Lnn` parameter to `M118` to have the message logged at the given level
* Add logging for G10, M291, M292
* Add current version to start of logging
* Make all non-flagged messages being part of log level DEBUG
> Extended logging

- src/Networking/W5500Ethernet/Wiznet/Internet/DHCP/dhcp.cpp
There is a small typo in src/Networking/W5500Ethernet/Wiznet/Internet/DHCP/dhcp.cpp.
Should read `changed` rather than `chaged`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, chaged -> changed

- src/Movement/DDARing.cpp
- src/Movement/DDARing.h
- src/Movement/Move.cpp
- src/Movement/Move.h
This adds the `M595 Rnn` word to set a grace period, that is waited out before starting into moves. The grace period will make sure fine-grained, high volume move sequences will be received in full and can be look-ahead-planned properly, without rushing into premature deceleration. 
The `R` word is given in milliseconds and controls the command reception idle time that tells the `Move::Spin()`, that no more move command are pending. Note that `M400` (and others) will release the motion sequence immediately. A motion sequence closed with `M400` will therefore incur no additional wait time. 
The default grace period is 0ms, leaving everything as it was. 
This option has been introduced after it was demonstrated that Duet would rush into premature deceleration on fine-grained interpolation …
> Feature / Configurable Grace Period for Starting into Moves

- src/Movement/Kinematics/HangprinterKinematics.cpp
This problem with Hangprinter's InverseTransform was found, debugged, and fixed in the old 2018-2019 hangprinter-branch.
Simply copied the fix over now.
> Avoids sqrtf of possibly negative number

- src/Movement/Kinematics/HangprinterKinematics.cpp
- src/Movement/Kinematics/HangprinterKinematics.h
There's nothing special about the D-anchor.
Allowing it to have non-zero xy-locations is very useful,
especially when auto-calibrating the anchor locations with help
of computer vision.
Code also gets easier to maintain, with less implicit knowledge
about Hangprinters needed.
The cost of this niceness is that the binary gets 164 bytes bigger.
I will place the line buildup compensation commit on top of this one, in the hope that 164 bytes is a manageable cost.
> Removes special handling of Hangprinter's D-anchor
